package-managers:
  app:
    windows: [ scoop, choco, npm, pip, cargo ]
    ubuntu: [ apt, npm, pip, cargo, snap ]
    darwin: [ brew, npm, pip, cargo ]
  font:
    windows: [ scoop ]
    ubuntu: []
    darwin: [ brew ]
  driver:
    any: []
  provisioned:
    windows: [ appx ]
  backend:
    python:
      any: [ pip ]
    node:
      any: [ npm ]
  extension:
    vscode:
      any: [ vscode-extension ]
tags:
  - cli
  - gui
  - books
  - browser
  - cloud
  - communication
  - dev-tools
  - db
  - editor
  - media
  - music
  - network
  - notes
  - package-manager
  - prog-langs
  - reference
  - security
  - sysadmin
  - utils
  - web-server
